source 'https://github.com/CocoaPods/Specs.git'

target 'PHNScrollViewPicker', :exclusive => true do
  pod "PHNScrollViewPicker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PHNScrollViewPicker", :path => "../"

  
end
